// Tony Hawk's Project 8 - Game-specific function overrides
//
// This file contains overrides for game functions that need special handling
// on PC. These replace the weak aliases generated by codegen.

#include "thp8_init.h"

#include <rex/ppc/context.h>
#include <rex/logging.h>
#include <cstdio>

// ============================================================================
// Memcpy / memset null-destination guard (diagnostic override)
// ============================================================================
//
// sub_823A9358 is the game's inline memcpy. If the destination pointer is null
// (or suspiciously small), it will AV writing to guest address 0x00–0x7F.
// This override logs the call and skips the copy to avoid the crash, letting
// us see the LR (return address) to identify the upstream caller.

extern "C" REX_FUNC(__imp__sub_823A9358);

extern "C" REX_FUNC(sub_823A9358) {
    REX_FUNC_PROLOGUE();
    uint32_t dst = ctx.r3.u32;
    uint32_t src = ctx.r4.u32;
    uint32_t len = ctx.r5.u32;
    if (dst < 0x1000) {
        REXLOG_ERROR(
            "sub_823A9358: NULL/near-null dst={:08X} src={:08X} len={:08X} lr={:08X}",
            dst, src, len, (uint32_t)ctx.lr);
        // Skip the copy to avoid AV; let the game continue so we can see
        // subsequent log entries that identify the source of the null.
        ctx.r3.u64 = dst; // preserve return value (destination)
        return;
    }
    __imp__sub_823A9358(ctx, base);
}

// ============================================================================
// Heap Sentinel Fix
// ============================================================================

// sub_823AE680: Heap free-list insertion.
// The free-list uses self-referential sentinel nodes at heap_base+384 (128 slots × 8 bytes).
// If the heap manager is freshly zeroed, the sentinel is 0 instead of self-referential,
// causing an infinite traversal loop.
// We detect broken sentinels and repair them before delegating to the real implementation.

extern "C" REX_FUNC(__imp__sub_823AE680);

extern "C" REX_FUNC(sub_823AE680) {
    REX_FUNC_PROLOGUE();
    uint32_t heap_base = ctx.r3.u32;
    if (heap_base) {
        // 128 slots × 8 bytes starting at heap_base+384
        uint32_t r11 = heap_base + 384;
        for (int i = 0; i < 128; ++i, r11 += 8) {
            if (REX_LOAD_U32(r11) == 0) {
                REX_STORE_U32(r11,     r11);
                REX_STORE_U32(r11 + 4, r11);
            }
        }
        // Extra sentinel node used for large-bin list
        r11 += 88;
        if (REX_LOAD_U32(r11) == 0) {
            REX_STORE_U32(r11,     r11);
            REX_STORE_U32(r11 + 4, r11);
        }
        // Repair small-bin sentinel at heap_base+88
        uint32_t sbin = heap_base + 88;
        if (REX_LOAD_U32(sbin) == 0) {
            REX_STORE_U32(sbin,     sbin);
            REX_STORE_U32(sbin + 4, sbin);
        }
    }
    __imp__sub_823AE680(ctx, base);
}

// ============================================================================
// Disc / Platform Path Overrides
// ============================================================================

// sub_823A13A8: disc path validity checker.
// Returns 1 if path is a "disc device" path that failed I/O (triggers dirty disc UI).
// On PC we always return 0 (path is valid, no disc error) to bypass Xbox disc checks.
extern "C" REX_FUNC(sub_823A13A8) {
    REX_FUNC_PROLOGUE();
    ctx.r3.u64 = 0; // 0 = path is valid, no dirty disc
}

// sub_82360B88: called immediately before XamShowDirtyDiscErrorUI.
// Suppress it on PC — we don't have a disc error dialog.
extern "C" REX_FUNC(sub_82360B88) {
    REX_FUNC_PROLOGUE();
    REXLOG_WARN("sub_82360B88 (dirty disc error UI) suppressed on PC");
}

// sub_823983B0: C++ destructor/cleanup thunk called virtually in a loop with null sub-object.
// Prevent crash by returning 0 instead of performing the bad virtual call.
extern "C" REX_FUNC(sub_823983B0) {
    REX_FUNC_PROLOGUE();
    ctx.r3.u64 = 0;
}

// ============================================================================
// Ring Buffer Queue Worker Fix
// ============================================================================
//
// The Xbox 360 uses ring buffers + worker threads for GPU commands and async I/O.
// Sub_823A67B8 pushes items to a ring buffer; trap instructions signal workers.
// In ReXGlue, ppc_trap() is a no-op — workers never wake — deadlock.
//
// Two separate systems use different queue_managers (qm):
//
// Async I/O (sub_823A2890): slots have type 0/1; processed by sub_823A25E8.
//   Fix: intercept sub_823A67B8 in ASYNC_IO context and call sub_823A25E8
//   synchronously, just as the Xbox 360 worker thread would.
//
// GPU commands (sub_823A2ED0/sub_823A2FF0): slots have type 4; processed by
//   the "GPU Commands" XThread (sub_823A4DC0 loop → sub_823A38E8). That thread
//   runs as a real host thread so it handles completions concurrently.
//   Problem: the GPU free list (*(qm+568)) can be empty on first call (the
//   ppc_trap assertion that would stall until a slot returns is a no-op), so
//   dequeue returns 0. Pushing null slot 0 to the work queue crashes the GPU
//   Commands thread when it reads slot[276] at guest address 276.
//   Fix: in sub_823A67B8 detect null (slot==0) before pushing, skip the push,
//   and clear *(cmd_obj+212) so sub_823A4700's spin loop exits immediately.

enum SubmitContext { CTX_NONE, CTX_ASYNC_IO, CTX_GPU };
static thread_local SubmitContext g_submit_ctx = CTX_NONE;
static thread_local uint32_t g_async_qm = 0;
// cmd_obj captured from the caller's r31 (= command_obj in sub_823A4700) so
// sub_823A67B8 can clear *(cmd_obj+212) if a null slot is detected.
static thread_local uint32_t g_gpu_cmd_obj = 0;

extern "C" REX_FUNC(__imp__sub_823A2890);
extern "C" REX_FUNC(__imp__sub_823A2ED0);
extern "C" REX_FUNC(__imp__sub_823A2FF0);
extern "C" REX_FUNC(__imp__sub_823A67B8);
extern "C" REX_FUNC(sub_823A25E8);

// sub_823A2890: async I/O submit — set ASYNC_IO context so sub_823A67B8 knows
// to dispatch inline via sub_823A25E8.
extern "C" REX_FUNC(sub_823A2890) {
    REX_FUNC_PROLOGUE();
    g_async_qm = ctx.r3.u32;
    SubmitContext old_ctx = g_submit_ctx;
    g_submit_ctx = CTX_ASYNC_IO;
    __imp__sub_823A2890(ctx, base);
    g_submit_ctx = old_ctx;
}

// sub_823A67B8: ring buffer push.
// In ASYNC_IO context: dispatch slot inline via sub_823A25E8 (avoids deadlock
// since workers don't run). Recursive calls (from within sub_823A25E8 for
// free-list return or secondary pushes) use the real ring buffer push.
// In all other contexts: perform the real ring buffer push normally.
// Special case: if the slot pointer dereferences to 0 (null), skip the push
// entirely — null slots arise when the GPU free list is empty and ppc_trap
// (which in hardware stalls until a slot is returned) is a no-op. Pushing 0
// crashes the GPU Commands worker thread. Instead we force-clear the spin-flag
// *(g_gpu_cmd_obj+212) so sub_823A4700's wait loop exits immediately.
extern "C" REX_FUNC(sub_823A67B8) {
    REX_FUNC_PROLOGUE();
    thread_local bool in_async_dispatch = false;
    if (g_submit_ctx == CTX_ASYNC_IO && !in_async_dispatch) {
        uint32_t slot_ptr = REX_LOAD_U32(ctx.r4.u32); // dereference: *(r4) = slot address
        in_async_dispatch = true;
        ctx.r3.u32 = g_async_qm;
        ctx.r4.u32 = slot_ptr;
        ctx.r5.u32 = 0;
        sub_823A25E8(ctx, base);
        in_async_dispatch = false;
    } else {
        uint32_t slot = ctx.r4.u32 ? REX_LOAD_U32(ctx.r4.u32) : 0;
        if (slot == 0) {
            REXLOG_WARN("sub_823A67B8: null GPU slot push suppressed; forcing command completion");
            if (g_gpu_cmd_obj) REX_STORE_U32(g_gpu_cmd_obj + 212, 0);
            return;
        }
        __imp__sub_823A67B8(ctx, base);
    }
}

// sub_823A2ED0: GPU command submit.
// Set g_gpu_cmd_obj so sub_823A67B8 can clear *(cmd_obj+212) if a null slot
// is detected (empty free list + ppc_trap no-op). The GPU Commands worker
// thread (sub_823A4DC0 → sub_823A38E8) handles completion for valid slots.
extern "C" REX_FUNC(sub_823A2ED0) {
    REX_FUNC_PROLOGUE();
    g_gpu_cmd_obj = ctx.r31.u32; // caller's r31 = command_obj (sub_823A4700)
    SubmitContext old_ctx = g_submit_ctx;
    g_submit_ctx = CTX_GPU;
    __imp__sub_823A2ED0(ctx, base);
    g_submit_ctx = old_ctx;
    g_gpu_cmd_obj = 0;
}

// sub_823A2FF0: additional GPU command submit — same as sub_823A2ED0.
extern "C" REX_FUNC(sub_823A2FF0) {
    REX_FUNC_PROLOGUE();
    g_gpu_cmd_obj = ctx.r31.u32;
    SubmitContext old_ctx = g_submit_ctx;
    g_submit_ctx = CTX_GPU;
    __imp__sub_823A2FF0(ctx, base);
    g_submit_ctx = old_ctx;
    g_gpu_cmd_obj = 0;
}

// ============================================================================
// ISB Completion Checker
// ============================================================================

// sub_823ABCD0: checks ISB status and stores result to output buffer.
// r3=unused, r4=ISB_ptr, r5=output_ptr, r6=wait_flag
extern "C" REX_FUNC(sub_823ABCD0) {
    REX_FUNC_PROLOGUE();
    uint32_t isb_ptr = ctx.r4.u32;
    if (isb_ptr) {
        uint32_t isb_status = REX_LOAD_U32(isb_ptr + 0);
        // If still PENDING, force to SUCCESS (worker threads don't run)
        if (isb_status == 0x00000103u) {
            REX_STORE_U32(isb_ptr, 0);
            isb_status = 0;
        }
        if ((int32_t)isb_status < 0) {
            ctx.r3.u64 = 0;
        } else {
            if (ctx.r5.u32) REX_STORE_U32(ctx.r5.u32, REX_LOAD_U32(isb_ptr + 4));
            ctx.r3.u64 = 1;
        }
    } else {
        ctx.r3.u64 = 0;
    }
}

// ============================================================================
// Stream Buffer Flush — Null Output Guard
// ============================================================================
//
// sub_821E4348: flushes a decompression stream's internal buffer to the output
// destination.  The stream object (r3) has:
//   +0  = base output pointer
//   +4  = pending byte count
//   +20 = write offset
//   +24 = read offset
//
// If the output pointer is null (the caller failed to allocate the destination
// buffer), the original code memcpys to guest address 0 → access violation.
// After the copy it advances base_ptr += pending, corrupting state.
//
// Fix: detect null base_ptr, clear pending counters, and return early.

extern "C" REX_FUNC(__imp__sub_821E4348);

extern "C" REX_FUNC(sub_821E4348) {
    REX_FUNC_PROLOGUE();
    uint32_t base_ptr = REX_LOAD_U32(ctx.r3.u32 + 0);
    if (base_ptr == 0) {
        REXLOG_ERROR(
            "sub_821E4348: null output buffer in stream {:08X}, pending={:08X} lr={:08X}",
            ctx.r3.u32, REX_LOAD_U32(ctx.r3.u32 + 4), (uint32_t)ctx.lr);
        // Clear pending state to prevent repeated flush attempts and
        // avoid advancing the null pointer.
        REX_STORE_U32(ctx.r3.u32 + 4, 0);
        return;
    }
    __imp__sub_821E4348(ctx, base);
}
